DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(EMP_NO NUMBER(3),
EMP_NAME VARCHAR2(30),
DEPT VARCHAR2(30),
BASIC_SALARY NUMBER(10,2),
DA NUMBER(10,2),
HRA NUMBER(10,2),
CCA NUMBER(10,2),
GROSS NUMBER(10,2),
PF NUMBER(10,2),
NET NUMBER(10,2));

/***********CREATING TRIGGER*************/
CREATE OR REPLACE TRIGGER EMP_TRIG
BEFORE INSERT OR UPDATE ON EMPLOYEE
FOR EACH ROW
DECLARE
V_DA NUMBER;
V_HRA NUMBER;
V_CCA NUMBER;
V_GROSS NUMBER;
V_PF NUMBER;
V_NET NUMBER;
V_DEPT VARCHAR2(30);
BEGIN
	V_DEPT:=:NEW.DEPT;
	IF V_DEPT='SALES' THEN
		V_DA:=0.03;
		V_HRA:=0.04;
		V_CCA:=0.10;
		V_PF:=0.12;
	ELSIF V_DEPT='ACCOUNT' THEN
		V_DA:=0.05;
		V_HRA:=0.07;
		V_CCA:=0.12;
		V_PF:=0.15;

	ELSIF V_DEPT='COMPUTER' THEN
		V_DA:=0.05;
		V_HRA:=0.10;
		V_CCA:=0.15;
		V_PF:=0.20;

	ELSE 
		V_DA:=0.08;
		V_HRA:=0.10;
		V_CCA:=0.15;
		V_PF:=0.20;

	END IF;
	V_DA:=:NEW.BASIC_SALARY*V_DA;
	V_HRA:=:NEW.BASIC_SALARY*V_HRA;
	V_CCA:=:NEW.BASIC_SALARY*V_CCA;
	V_GROSS:=:NEW.BASIC_SALARY+V_DA+V_HRA+V_CCA;
	V_PF:=:NEW.BASIC_SALARY*V_PF;
	V_NET:=V_GROSS-V_PF;
	
	:NEW.DA:=V_DA;
	:NEW.HRA:=V_HRA;
	:NEW.CCA:=V_CCA;
	:NEW.GROSS:=V_GROSS;
	:NEW.PF:=V_PF;
	:NEW.NET:=V_NET;
END;
/
 

/****************INSERT RECORD***************************/

INSERT INTO EMPLOYEE (EMP_NO,EMP_NAME,DEPT,BASIC_SALARY)
VALUES (1,'A','COMPUTER',10000);
