DECLARE
	RGB CHAR(1);
BEGIN
	RGB:='&RGB';
	
	IF RGB='R' OR RGB='r' THEN
		DBMS_OUTPUT.PUT_LINE('YOU HAVE CHOOSEN RED COLOR');
	END IF;

	IF RGB='G' OR RGB='g' THEN
		DBMS_OUTPUT.PUT_LINE('YOU HAVE CHOOSEN GREEN COLOR');
	END IF;

	IF RGB='B' OR RGB='b' THEN
		DBMS_OUTPUT.PUT_LINE('YOU HAVE CHOOSEN BLUE COLOR');
	END IF;
END;
/